# Moved data step outside the init
# Added footnote
# Added App inf page
# Added variable browser, data table modules 
#install.packages("sparkline")
library(shiny)
library(sparkline)
library(teal.modules.general)
library(teal.modules.clinical)
library(rsconnect)

ADSL <- teal.modules.clinical::tmc_ex_adsl
ADAE <- teal.modules.clinical::tmc_ex_adae
ADTTE <- teal.modules.clinical::tmc_ex_adtte

## Load in data
data <- cdisc_data(
  ADSL = ADSL,
  ADAE = ADAE,
  ADTTE = ADTTE,
  code = "
      ADSL <- teal.modules.clinical::tmc_ex_adsl
      ADAE <- teal.modules.clinical::tmc_ex_adae
      ADTTE <- teal.modules.clinical::tmc_ex_adtte
    "
)

footer <- tags$p(
  "This teal app was created by following Shiny Gathering 2024 Teal Workshop"
)


app <- init(
  data = data,
  modules = modules(
    tm_front_page(
      label = "App Info",
      header_text = c("Info about input data source" = "This app uses CDISC ADaM datasets randomly generated by `random.cdisc.data` R packages"),
      tables = list(`NEST packages used in this demo app` = data.frame(
        Packages = c(
          "teal.modules.general",
          "teal.modules.clinical",
          "random.cdisc.data"
        )
      ))
    ),
    tm_data_table("Data Table"),
    tm_variable_browser("Variable Browser"), 
    tm_t_summary(
      label = "Demographic Table",
      dataname = "ADSL",
      arm_var = choices_selected(choices = c("ARM", "ARMCD"), selected = "ARM"),
      summarize_vars = choices_selected(
        choices = c("SEX", "RACE", "BMRKR2", "EOSDY", "DCSREAS", "AGE"),
        selected = c("SEX", "RACE", "BMRKR2")
      )
    ),
    tm_t_events(
      label = "AE Table",
      dataname = "ADAE",
      arm_var = choices_selected(choices = c("ARM", "ARMCD"), selected = "ARM"),
      hlt = choices_selected(
        choices = variable_choices(ADAE, c("AEBODSYS", "AESOC")),
        selected = "AEBODSYS"
      ),
      llt = choices_selected(
        choices = variable_choices(ADAE, c("AETERM", "AEDECOD")),
        selected = c("AEDECOD")
      )
    ),
    tm_g_km(
      label = "KM Plot",
      dataname = "ADTTE",
      arm_var = choices_selected(choices = c("ARM", "ARMCD", "ACTARMCD"), selected = "ARM"),
      paramcd = choices_selected(choices = value_choices(ADTTE, "PARAMCD", "PARAM"), selected = "OS"),
      strata_var = choices_selected(variable_choices(ADSL, c("SEX", "BMRKR2")), NULL),
      facet_var = choices_selected(variable_choices(ADSL, c("SEX", "BMRKR2")), NULL),
      plot_height = c(600L, 400L, 5000L),
    )
  ),
  header = tags$h1("My First Teal Shiny Application"),
  footer = footer,
  filter = teal_slices(
    teal_slice("ADSL", "SAFFL", id = "saffl", selected = "Y", fixed = TRUE, anchored = TRUE),
    teal_slice("ADAE", "AESER", anchored = TRUE),
    teal_slice("ADAE", id = "aerel", expr = "AEREL == 'Y' & AETOXGR %in% c('3', '4', '5')", title = "Grade 3+ Related Events"),
    teal_slice("ADSL", "SEX", id = "sex", fixed = TRUE),
    teal_slice("ADSL", id = "age", expr = "AGE >= 18 & AGE <= 30", title = "Young Adult"),
    module_specific = TRUE,
    mapping = list(
      "Demographic Table" = c("saffl"),
      "AE Table" = c("saffl", "aerel"),
      global_filters = c("sex", "age")
    ),
    count_type = "all"
  )
)

shinyApp(app$ui, app$server)

#install.packages('rsconnect'). # this version may not work with teal/nest package
# Step 2: The rsconnect package must be authorized to your account using a token and secret. 
# To do this, click the copy button below and we'll copy the whole command you need to your 
# clipboard. Paste it into your R console to authorize your account. Once you've entered the 
# command successfully in R, that computer is now authorized to deploy Shiny for R applications 
# to your shinyapps.io account.
#rsconnect::setAccountInfo(name='alanliu-penguin', token='AABD3E04534E1DA3A157DD875E6935F7', secret='GEZzNd2T+/1x6JiH/47w233Jhpx7cB1mgafO9ZV+')

# Step 3: deploy
# Once the rsconnect package has been configured, you're ready to deploy your first application.
# if you haven't written any applications yet, you can also checkout the Getting Started Guide 
# for instructions on how to deploy our demo application. Run the following code in your R console.
#library(rsconnect)
#rsconnect::deployApp('path/to/your/app')

